include("src/main.jl")
main("OOA_tests/lin_adv_p3_cDG_GLGL.csv")
main("OOA_tests/lin_adv_p3_cHU_GLGL.csv")
main("OOA_tests/lin_adv_p4_cDG_GLGL.csv")
main("OOA_tests/lin_adv_p4_cHU_GLGL.csv")
main("OOA_tests/lin_adv_p3_cDG_GLLGL.csv")
main("OOA_tests/lin_adv_p3_cHU_GLLGL.csv")
main("OOA_tests/lin_adv_p4_cDG_GLLGL.csv")
main("OOA_tests/lin_adv_p4_cHU_GLLGL.csv")
display("Ran successfully!")
